name: Run Playwright Tests

on:
  schedule:
    - cron: '0 18 * * 1'  # Todos los lunes a las 15:00 GMT-3
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run UI tests
        env:
          ENV: QA
          QA_URL: ${{ secrets.QA_URL }}
        run: npx playwright test ui-tests --headed=false
        continue-on-error: true
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-ui-${{ github.run_id }}
          path: playwright-report/
          retention-days: 30

      - name: Run API tests
        env:
          ENV: QA
          QA_URL: ${{ secrets.QA_URL }}
        run: npx playwright test api-tests --headed=false
        continue-on-error: true
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-api-${{ github.run_id }}
          path: playwright-report/
          retention-days: 30
          