name: Run Playwright Tests

on:
  schedule:
    - cron: '0 18 * * 1'  # Todos los lunes a las 15:00 GMT-3
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Create directories for artifacts
        run: |
          mkdir -p playwright-report/traces
          mkdir -p playwright-report/videos
          mkdir -p screenshots

      - name: Run UI tests
        env:
          ENV: QA
          QA_URL: ${{ secrets.QA_URL }}
        run: npx playwright test ui-tests --config=playwright.config.ts
        continue-on-error: true

      - name: Run API tests
        env:
          ENV: QA
          QA_URL: ${{ secrets.QA_URL }}
        run: npx playwright test api-tests --config=playwright.config.ts
        continue-on-error: true

      - name: Upload Playwright traces
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: playwright-report/traces/

      - name: Upload Playwright videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-videos
          path: playwright-report/videos/

      - name: Upload Playwright screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-screenshots
          path: screenshots/

      - name: Check for test failures
        if: always()
        run: |
          if grep -q 'FAIL' playwright-report/*.json; then
            echo "Tests failed"
            exit 1
          else
            echo "All tests passed"
          fi